# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mymodule', [dirname(__file__)])
        except ImportError:
            import _mymodule
            return _mymodule
        if fp is not None:
            try:
                _mod = imp.load_module('_mymodule', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mymodule = swig_import_helper()
    del swig_import_helper
else:
    import _mymodule
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class MySorter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MySorter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MySorter, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mymodule.new_MySorter()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _mymodule.delete_MySorter
    __del__ = lambda self: None

    def InitializeData(self, n=0, d=0):
        return _mymodule.MySorter_InitializeData(self, n, d)

    def setFeature(self, sample=0, feature=0, value=0):
        return _mymodule.MySorter_setFeature(self, sample, feature, value)

    def setBij(self, i=0, j=0, value=0):
        return _mymodule.MySorter_setBij(self, i, j, value)

    def setLabel(self, sample=0, label=0):
        return _mymodule.MySorter_setLabel(self, sample, label)

    def computeDistanceBetweenTwoPoint(self, i=0, j=0):
        return _mymodule.MySorter_computeDistanceBetweenTwoPoint(self, i, j)

    def computeTopRiPoints(self, k=10):
        return _mymodule.MySorter_computeTopRiPoints(self, k)

    def getIndexForTopList(self, index=0, coordinate=0):
        return _mymodule.MySorter_getIndexForTopList(self, index, coordinate)

    def getValueForTopList(self, index=0):
        return _mymodule.MySorter_getValueForTopList(self, index)

    def computeDistanceVialation(self, epsilon=0):
        return _mymodule.MySorter_computeDistanceVialation(self, epsilon)

    def MethodB(self, a=5):
        return _mymodule.MySorter_MethodB(self, a)

    def GetValA(self):
        return _mymodule.MySorter_GetValA(self)
MySorter_swigregister = _mymodule.MySorter_swigregister
MySorter_swigregister(MySorter)

# This file is compatible with both classic and new-style classes.


